stages:
  - build
  - github-push


variables:
  CI_GITHUB_REP_URL: github.com/DrDeLaBill/stm_builder.git


build:
  tags:
    - shell
    
  stage: build

  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY

  script:
    - |
      docker build . \
          -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME \
          --build-arg BUILD_VERSION="$CI_COMMIT_REF_SLUG-$CI_PIPELINE_IID" \
          --build-arg BUILD_DATE="$(date +%Y%m%d_%H%M%S)" \
          --build-arg BUILD_MIRROR_URL="$CI_MIRROR_URL"
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME


github-push:
  tags:
    - shell
    
  stage: github-push

  script:
    - git remote set-url origin https://$CI_GITHUB_TOKEN@$CI_GITHUB_REP_URL
    - git push origin $CI_COMMIT_REF_NAME 