name: Build and push docker image

on:
  push:
    branches: [ "main" ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - id: actor
      uses: vishalmamidi/lowercase-action@v1
      with:
        string: ${{ github.actor }}
    - id: image_name
      uses: vishalmamidi/lowercase-action@v1
      with:
        string: ${{ github.actor }}
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ steps.actor.outputs.lowercase }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ steps.image_name.outputs.lowercase }}:latest
          ${{ env.REGISTRY }}/${{ steps.image_name.outputs.lowercase }}:${{ github.sha }}
